const types = {
    APP_REQUEST :"APP_REQUEST",
    APP_SUCCESS :"APP_SUCCESS",
    APP_FAILURE :"APP_FAILURE",

    REGISTER_REQUEST :"REGISTER_REQUEST",
    REGISTER_SUCCESS :"REGISTER_SUCCESS",
    REGISTER_FAILURE :"REGISTER_FAILURE",

    LOGIN_REQUEST :"LOGIN_REQUEST",
    LOGIN_SUCCESS :"LOGIN_SUCCESS",
    LOGIN_FAILURE :"LOGIN_FAILURE",
}

export default types;